=== UsirkepallyVarsha/HireHub/hireHub/xml/students.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (name, email, branch, cgpa, attendance, mobile)>
<!ATTLIST student id CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT cgpa (#PCDATA)>
<!ELEMENT attendance (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>

=== UsirkepallyVarsha/HireHub/hireHub/xml/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>

<!DOCTYPE students SYSTEM "students.dtd">

<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="students.xsd">

  <student id="S101">
    <name>Pavithra</name>
    <email>pavithra@gmail.com</email>
    <branch>IT</branch>
    <cgpa>8.5</cgpa>
    <attendance>92</attendance>
    <mobile>9876543210</mobile>
  </student>

  <student id="S102">
    <name>Chand</name>
    <email>chand@gmail.com</email>
    <branch>CSE</branch>
    <cgpa>8.2</cgpa>
    <attendance>88</attendance>
    <mobile>9123456789</mobile>
  </student>

</students>
